### ISSUE TITLE
Alternative to LESS?

### ISSUE THREAD

**Issue by georgebarnick** [codynguyen1116/brickimedia-design-guide#2]
I've never used LESS before but from what I can see of it here, I'm not impressed nor satisfied with it. First of all, and most noticeably, even something as simple as ```index.html```'s ```#header``` isn't getting any styles anymore, which it was yesterday. Next, it does not fail gracefully with XHR, which it shouldn't even need to be doing. It's looking in the wrong places for files, and I've tried using local sources (which shouldn't even be loaded over XHR at all...) and absolute URLs, neither of which are working. Even with an <b>absolute</b> URL, it's still trying to find resources somewhere else. Wtf??

![image](https://cloud.githubusercontent.com/assets/3800972/12022428/b8f5f29e-ad5d-11e5-89cb-a1f39455f2c1.png)

I can't even debug this anymore because it's basically the worst library I've ever used, so if there are any alternatives that don't involve insecure loading of local resources and utter retardedness, that'd be great to switch to.

**Comment by codynguyen1116** [comment]
There's the SASS (Syntactically Awesome Style Sheets) preprocessor and there's also the SCSS version of it. Haven't looked too much at it but I've been reading on articles about them and documentation like these:
https://css-tricks.com/sass-vs-less/
http://thesassway.com/editorial/sass-vs-scss-which-syntax-is-better
http://www.hongkiat.com/blog/sass-vs-less/
http://www.smashingmagazine.com/2011/09/an-introduction-to-less-and-comparison-to-sass/
http://thesassway.com/

**Comment by georgebarnick** [comment]
Please review my last commit. I think it fixes some of the issues but there's still quite a bit of errors stacking up. Is there a more elegant way to load these resources without ```@import```s all over the place in the ```.less``` files?

**Comment by codynguyen1116** [comment]
Something's wrong with the colour palette file so I'll look into that, although no there doesn't appear to be any other way so far.  Here are some examples from [Google MDL](https://github.com/google/material-design-lite) that do the same thing.  (__Note:__ although this _is_ in SCSS it still uses the ```@import``` method)
- https://github.com/google/material-design-lite/blob/master/src/grid/_grid.scss
- https://github.com/google/material-design-lite/blob/master/src/button/_button.scss
- https://github.com/google/material-design-lite/blob/master/src/shadow/_shadow.scss

**Comment by codynguyen1116** [comment]
Commit https://github.com/codynguyen1116/brickimedia-design-guide/commit/16a72dc0a19489bbc589b7506e205c0af1b9eea0 should fix the error that says "Uncaught ReferenceError: $ is not defined" since the jQuery library wasn't imported before,although I don't know how to fix the "Uncaught (in promise) b.exports" issue (tbh I don't understand what its saying). Do you know what it means @georgebarnick ?

![image](https://cloud.githubusercontent.com/assets/4723983/12026071/f2c83884-ad7a-11e5-81f8-e3b17a40bf75.png)

**Comment by MtMNC** [comment]
@codynguyen1116 TBH I don't know what that error means, but it says it's happening on line 1 of variables.less. There it looks like you're trying to import color-palette.less but the actual file is named colour-palette.less, maybe that's the issue?

**Comment by codynguyen1116** [comment]
@MtMNC Yep that's it, thanks. :P (i feel stupid now haha) it's funny how one typo can cause so many errors. :P

**Comment by codynguyen1116** [comment]
Every issue shouldn't appear in the console now after https://github.com/codynguyen1116/brickimedia-design-guide/commit/59d0dc57d7a770f35c04d76a14b16f41e1922f62 and it was mainly because of stupid mistakes. However there is still the XMLHttpRequest caution which creates security holes and there still 's the decision of whether we want to keep LESS or switch to Sass/SCSS (keep in mind _both_ CSS preprocessors have a learning curve )

**Comment by MtMNC** [comment]
@codynguyen1116 Hey no worries, stuff like that happens to everyone!

Security holes shouldn't be an issue because (according to my understanding at least) usually CSS preprocessors are used for development, but only the processed files are actually deployed. So it's considered better practice to write in Less, then convert the Less into CSS, then you use the CSS files on the site instead of using the Less on the site. That way the browser doesn't have to run less.js on every page load for the CSS to show up. So @georgebarnick Less isn't bad for this project necessarily, I think this is an instance of it not being applied correctly. While the site is being developed it's easier to compile the Less in-browser, but when the design guide is done, CSS should be deployed instead and all the XHR problems should disappear.

If we're using a preprocessor, let's stick with Less if only because [that's the one MediaWiki uses](https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS#Less).

**Comment by georgebarnick** [comment]
@MtMNC: That's fine. I was going to oppose using LESS for deployment anyways because I've already noticed it makes pages sluggish to load. If load times are an issue on my server because of LESS, it'd only be worse when deployed to Brickimedia.

**Comment by codynguyen1116** [comment]
OK, I'll continue working on the design guide / live demo.
